# Generated by Django 4.1.3 on 2022-11-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='materials',
            field=models.CharField(choices=[('egg', 'EGG'), ('juice', 'JUICE'), ('milk', 'MILK'), ('bread', 'BREAD'), ('butter', 'BUTTER')], default='egg', max_length=10),
        ),
        migrations.AddField(
            model_name='supplier',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
