# Generated by Django 4.1.3 on 2022-11-24 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_practice', '0002_supplier_materials_supplier_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='shops_detail',
            new_name='supplying_to',
        ),
    ]
