# Generated by Django 4.1.3 on 2022-11-24 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_practice', '0003_rename_shops_detail_supplier_supplying_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='quantity',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materials', models.CharField(choices=[('egg', 'EGG'), ('juice', 'JUICE'), ('milk', 'MILK'), ('bread', 'BREAD'), ('butter', 'BUTTER')], default='egg', max_length=10)),
                ('quantity', models.IntegerField(default=0)),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_practice.shop')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_practice.supplier')),
            ],
        ),
    ]
