# Generated by Django 4.1.3 on 2022-11-24 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_practice', '0004_remove_supplier_materials_remove_supplier_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='supplying_to',
        ),
    ]
