# Generated by Django 4.1.3 on 2022-11-24 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_practice', '0006_delete_user_alter_order_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_detail', to='api_practice.supplier'),
        ),
    ]
