# Generated by Django 4.1.3 on 2022-11-24 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_practice', '0007_shop_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='materials',
            new_name='material',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shop',
        ),
    ]
