# Generated by Django 4.1.3 on 2022-11-24 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_practice', '0008_rename_materials_order_material_remove_order_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_practice.shop'),
        ),
    ]
